create table if not exists public.login_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
do $$
begin
  if exists (
    select 1
    from pg_constraint c
    where c.conrelid = 'public.login_events'::regclass
      and c.conname = 'login_events_user_id_fkey'
      and not (
        c.confdeltype = 'c'
        and c.confrelid = 'public.profiles'::regclass
        and exists (
          select 1
          from pg_attribute a
          where a.attrelid = c.conrelid
            and a.attname = 'user_id'
            and not a.attisdropped
            and c.conkey = array[a.attnum]::smallint[]
        )
        and exists (
          select 1
          from pg_attribute a
          where a.attrelid = c.confrelid
            and a.attname = 'id'
            and not a.attisdropped
            and c.confkey = array[a.attnum]::smallint[]
        )
      )
  ) then
    alter table public.login_events
      drop constraint login_events_user_id_fkey;
  end if;

  if not exists (
    select 1
    from pg_constraint c
    where c.conrelid = 'public.login_events'::regclass
      and c.conname = 'login_events_user_id_fkey'
      and c.confdeltype = 'c'
      and c.confrelid = 'public.profiles'::regclass
      and exists (
        select 1
        from pg_attribute a
        where a.attrelid = c.conrelid
          and a.attname = 'user_id'
          and not a.attisdropped
          and c.conkey = array[a.attnum]::smallint[]
      )
      and exists (
        select 1
        from pg_attribute a
        where a.attrelid = c.confrelid
          and a.attname = 'id'
          and not a.attisdropped
          and c.confkey = array[a.attnum]::smallint[]
      )
  ) then
    alter table public.login_events
      add constraint login_events_user_id_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade;
  end if;
end;
$$;
create index if not exists login_events_user_created_idx
  on public.login_events (user_id, created_at desc, id desc);

create or replace function public.record_login_event()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Authentication required to record a login event';
  end if;

  insert into public.login_events (user_id, created_at)
  values (v_user_id, now());
end;
$$;

revoke all on public.login_events from public, anon, authenticated;
grant select on public.login_events to authenticated;

alter table public.login_events enable row level security;

drop policy if exists login_events_admin_read on public.login_events;
create policy login_events_admin_read on public.login_events
  for select to authenticated
  using ((select public.is_admin()));

revoke all on function public.record_login_event() from public, anon, authenticated;
grant execute on function public.record_login_event() to authenticated;
