create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  first_name text not null default '',
  last_name text not null default '',
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  image_url text not null default 'assets/default-tech-placeholder.svg',
  price_php numeric(12, 2) not null default 0 check (price_php >= 0),
  discount_percent numeric(5, 2) not null default 0 check (discount_percent between 0 and 90),
  description text not null default '',
  stock integer not null default 0 check (stock >= 0),
  categories jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id),
  items jsonb not null default '[]'::jsonb,
  total numeric(12, 2) not null default 0 check (total >= 0),
  shipping_details jsonb not null default '{}'::jsonb,
  status text not null default 'completed' check (status in ('pending', 'completed', 'cancelled')),
  order_number text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0)
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id),
  product_id bigint not null references public.products(id),
  order_id bigint references public.orders(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  price_paid numeric(12, 2) not null check (price_paid >= 0),
  transaction_date timestamptz not null default now(),
  status text not null default 'completed'
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  user_name text not null,
  rating numeric(2, 1) not null check (rating between 1 and 5),
  rating_stars smallint not null check (rating_stars between 1 and 5),
  comment text not null,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.site_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default '',
  bio text not null default '',
  image_url text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, first_name, last_name)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', '')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

create or replace function public.set_bulk_discount(p_scope text, p_percent numeric)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_percent numeric(5, 2) := greatest(0, least(90, coalesce(p_percent, 0)));
  v_count integer;
begin
  if not public.is_admin() then
    raise exception 'Administrator access required';
  end if;

  update public.products
  set discount_percent = v_percent
  where coalesce(p_scope, 'all') = 'all'
     or categories @> jsonb_build_array(p_scope);
  get diagnostics v_count = row_count;

  return jsonb_build_object(
    'success', true,
    'updated', v_count,
    'percent', v_percent,
    'scope', coalesce(p_scope, 'all')
  );
end;
$$;

create or replace function public.place_order(
  p_items jsonb,
  p_shipping_details jsonb,
  p_order_number text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id bigint;
  v_item jsonb;
  v_saved_items jsonb := '[]'::jsonb;
  v_product public.products%rowtype;
  v_product_id bigint;
  v_quantity integer;
  v_unit_price numeric(12, 2);
  v_total numeric(12, 2) := 0;
begin
  if v_user_id is null then
    raise exception 'Please sign in before placing an order';
  end if;
  if coalesce(jsonb_typeof(p_items), '') <> 'array' then
    raise exception 'Order items must be a JSON array';
  end if;
  if jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 50 then
    raise exception 'The order must contain between 1 and 50 items';
  end if;

  insert into public.orders (user_id, items, total, shipping_details, status, order_number)
  values (
    v_user_id,
    '[]'::jsonb,
    0,
    coalesce(p_shipping_details, '{}'::jsonb),
    'completed',
    coalesce(nullif(p_order_number, ''), 'ORD-' || extract(epoch from clock_timestamp())::bigint::text)
  )
  returning id into v_order_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_product_id := coalesce(nullif(v_item ->> 'id', '')::bigint, nullif(v_item ->> 'product_id', '')::bigint);
    v_quantity := coalesce(nullif(v_item ->> 'quantity', '')::integer, 0);
    if v_product_id is null or v_quantity < 1 then
      raise exception 'Invalid product or quantity in order';
    end if;

    select * into v_product
    from public.products
    where id = v_product_id and active
    for update;
    if not found then
      raise exception 'Product % is unavailable', v_product_id;
    end if;
    if v_product.stock < v_quantity then
      raise exception 'Not enough stock for %', v_product.name;
    end if;

    v_unit_price := round(v_product.price_php * (1 - v_product.discount_percent / 100), 2);
    update public.products set stock = stock - v_quantity where id = v_product_id;
    insert into public.order_items (order_id, product_id, product_name, quantity, unit_price)
    values (v_order_id, v_product_id, v_product.name, v_quantity, v_unit_price);
    insert into public.transactions (user_id, product_id, order_id, product_name, quantity, price_paid, status)
    values (v_user_id, v_product_id, v_order_id, v_product.name, v_quantity, v_unit_price * v_quantity, 'completed');

    v_total := v_total + v_unit_price * v_quantity;
    v_saved_items := v_saved_items || jsonb_build_array(jsonb_build_object(
      'id', v_product.id,
      'name', v_product.name,
      'image_url', v_product.image_url,
      'price', v_unit_price,
      'quantity', v_quantity
    ));
  end loop;

  update public.orders
  set items = v_saved_items, total = v_total
  where id = v_order_id;

  return (select to_jsonb(o) from public.orders o where o.id = v_order_id);
end;
$$;

revoke all on public.profiles, public.products, public.orders, public.order_items,
  public.transactions, public.reviews, public.site_settings, public.team_members
  from anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;
revoke all on function public.set_bulk_discount(text, numeric) from public, anon;
grant execute on function public.set_bulk_discount(text, numeric) to authenticated;
revoke all on function public.place_order(jsonb, jsonb, text) from public, anon;
grant execute on function public.place_order(jsonb, jsonb, text) to authenticated;

grant usage on schema public to anon, authenticated;
grant select on public.products, public.reviews, public.site_settings, public.team_members to anon, authenticated;
grant select on public.profiles, public.orders, public.order_items, public.transactions to authenticated;
grant insert, update, delete on public.products, public.site_settings, public.team_members to authenticated;
grant insert, delete on public.reviews to authenticated;
revoke update on public.reviews from authenticated;
grant update (rating, rating_stars, comment) on public.reviews to authenticated;
grant update (first_name, last_name) on public.profiles to authenticated;
grant usage, select on sequence public.products_id_seq, public.orders_id_seq,
  public.order_items_id_seq, public.transactions_id_seq, public.reviews_id_seq,
  public.team_members_id_seq to authenticated;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.transactions enable row level security;
alter table public.reviews enable row level security;
alter table public.site_settings enable row level security;
alter table public.team_members enable row level security;

drop policy if exists profiles_read_self_or_admin on public.profiles;
create policy profiles_read_self_or_admin on public.profiles
  for select to authenticated
  using (id = (select auth.uid()) or (select public.is_admin()));
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
  for update to authenticated
  using (id = (select auth.uid()) or (select public.is_admin()))
  with check (id = (select auth.uid()) or (select public.is_admin()));

drop policy if exists products_read_active on public.products;
create policy products_read_active on public.products
  for select to anon, authenticated
  using (active or (select public.is_admin()));
drop policy if exists products_admin_insert on public.products;
create policy products_admin_insert on public.products
  for insert to authenticated with check ((select public.is_admin()));
drop policy if exists products_admin_update on public.products;
create policy products_admin_update on public.products
  for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists products_admin_delete on public.products;
create policy products_admin_delete on public.products
  for delete to authenticated using ((select public.is_admin()));

drop policy if exists orders_read_self_or_admin on public.orders;
create policy orders_read_self_or_admin on public.orders
  for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));
drop policy if exists order_items_read_owner_or_admin on public.order_items;
create policy order_items_read_owner_or_admin on public.order_items
  for select to authenticated
  using (
    exists (
      select 1 from public.orders o
      where o.id = order_id and (o.user_id = (select auth.uid()) or (select public.is_admin()))
    )
  );
drop policy if exists transactions_read_self_or_admin on public.transactions;
create policy transactions_read_self_or_admin on public.transactions
  for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));

drop policy if exists reviews_read_public on public.reviews;
create policy reviews_read_public on public.reviews
  for select to anon, authenticated using (true);
drop policy if exists reviews_insert_verified_purchase on public.reviews;
create policy reviews_insert_verified_purchase on public.reviews
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.transactions t
      where t.user_id = (select auth.uid())
        and t.product_id = reviews.product_id
        and t.status = 'completed'
    )
  );
drop policy if exists reviews_update_owner on public.reviews;
create policy reviews_update_owner on public.reviews
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));
drop policy if exists reviews_delete_owner_or_admin on public.reviews;
create policy reviews_delete_owner_or_admin on public.reviews
  for delete to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));

drop policy if exists site_settings_read_public on public.site_settings;
create policy site_settings_read_public on public.site_settings
  for select to anon, authenticated using (true);
drop policy if exists site_settings_admin_write on public.site_settings;
create policy site_settings_admin_write on public.site_settings
  for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists team_members_read_public on public.team_members;
create policy team_members_read_public on public.team_members
  for select to anon, authenticated using (true);
drop policy if exists team_members_admin_write on public.team_members;
create policy team_members_admin_write on public.team_members
  for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

insert into public.products (name, slug, image_url, price_php, description, stock, categories)
values
  ('Wireless Noise-Cancelling Headphones', 'wireless-noise-cancelling-headphones', 'assets/default-tech-placeholder.svg', 11399.00, 'Premium wireless headphones with active noise cancellation.', 15, '["electronics"]'::jsonb),
  ('Smart Watch Series 5', 'smart-watch-series-5', 'assets/default-tech-placeholder.svg', 28499.00, 'Advanced smartwatch with health monitoring and GPS.', 8, '["electronics", "wearables"]'::jsonb),
  ('Mechanical Gaming Keyboard', 'mechanical-gaming-keyboard', 'assets/default-tech-placeholder.svg', 19949.00, 'RGB mechanical keyboard with programmable macros.', 22, '["electronics", "accessories"]'::jsonb),
  ('27-inch 4K IPS Monitor', '27-inch-4k-ips-monitor', 'assets/default-tech-placeholder.svg', 24999.00, 'Ultra-sharp 4K display with 99% sRGB color coverage.', 10, '["electronics", "accessories"]'::jsonb),
  ('Bluetooth Gaming Mouse', 'bluetooth-gaming-mouse', 'assets/default-tech-placeholder.svg', 249.00, 'Lightweight wireless mouse with 16,000 DPI sensor.', 35, '["electronics", "accessories"]'::jsonb),
  ('USB-C Fast Charger 65W', 'usb-c-fast-charger-65w', 'assets/default-tech-placeholder.svg', 1799.00, 'GaN charger with dual USB-C ports for laptops and phones.', 40, '["electronics", "accessories"]'::jsonb),
  ('Noise-Cancelling Earbuds', 'noise-cancelling-earbuds', 'assets/default-tech-placeholder.svg', 6499.00, 'True wireless earbuds with transparency mode and IPX5 rating.', 25, '["electronics"]'::jsonb),
  ('Portable SSD 1TB', 'portable-ssd-1tb', 'assets/default-tech-placeholder.svg', 789.00, 'USB 3.2 external SSD with 1,050 MB/s transfer speeds.', 18, '["electronics", "accessories"]'::jsonb),
  ('Laptop Cooling Pad', 'laptop-cooling-pad', 'assets/default-tech-placeholder.svg', 1299.00, 'Five-fan cooling pad with adjustable height and RGB lighting.', 30, '["accessories"]'::jsonb),
  ('Webcam 1080p Pro', 'webcam-1080p-pro', 'assets/default-tech-placeholder.svg', 349.00, 'Full HD webcam with auto-focus and built-in noise-reducing mic.', 20, '["electronics", "accessories"]'::jsonb),
  ('Ergonomic Office Chair', 'ergonomic-office-chair', 'assets/default-tech-placeholder.svg', 12999.00, 'Mesh-back chair with lumbar support and adjustable armrests.', 7, '["accessories"]'::jsonb),
  ('Standing Desk Converter', 'standing-desk-converter', 'assets/default-tech-placeholder.svg', 9499.00, 'Height-adjustable desk riser that fits dual monitors.', 9, '["accessories"]'::jsonb),
  ('Fitness Tracker Band', 'fitness-tracker-band', 'assets/default-tech-placeholder.svg', 289.00, 'Slim band with heart-rate monitor, sleep tracking and 14-day battery.', 28, '["electronics", "wearables"]'::jsonb),
  ('Wireless Charging Pad', 'wireless-charging-pad', 'assets/default-tech-placeholder.svg', 1099.00, '15W Qi fast charging pad with anti-slip silicone surface.', 45, '["electronics", "accessories"]'::jsonb),
  ('External HDD 2TB', 'external-hdd-2tb', 'assets/default-tech-placeholder.svg', 569.00, 'Portable 2.5-inch hard drive with shock-resistant casing.', 16, '["electronics", "accessories"]'::jsonb),
  ('Streaming Microphone', 'streaming-microphone', 'assets/default-tech-placeholder.svg', 5299.00, 'USB condenser mic with cardioid pickup and zero-latency monitoring.', 14, '["electronics"]'::jsonb),
  ('Gaming Headset with Mic', 'gaming-headset-with-mic', 'assets/default-tech-placeholder.svg', 3999.00, 'Surround-sound headset with detachable noise-cancelling boom mic.', 19, '["electronics", "accessories"]'::jsonb),
  ('Smart Light Bulb (4-Pack)', 'smart-light-bulb-4-pack', 'assets/default-tech-placeholder.svg', 2199.00, 'WiFi bulbs with 16M colors, app and voice control.', 26, '["electronics"]'::jsonb),
  ('Tablet 10.1-inch 64GB', 'tablet-10-1-inch-64gb', 'assets/default-tech-placeholder.svg', 11499.00, '10.1-inch FHD tablet with octa-core CPU and dual speakers.', 11, '["electronics"]'::jsonb),
  ('Power Bank 20,000mAh', 'power-bank-20000mah', 'assets/default-tech-placeholder.svg', 1899.00, 'Dual-output power bank with USB-C PD fast charging.', 33, '["electronics", "accessories"]'::jsonb),
  ('HDMI 2.1 Cable 2m', 'hdmi-2-1-cable-2m', 'assets/default-tech-placeholder.svg', 749.00, '8K-ready braided HDMI cable with eARC support.', 50, '["electronics", "accessories"]'::jsonb)
on conflict (slug) do nothing;

insert into public.site_settings (key, value)
values
  ('brand_name', 'ByteCart'),
  ('announcement_text', 'Welcome to Byte Cart'),
  ('copyright_text', '© 2026 ByteCart. All rights reserved.'),
  ('social_links', '[{"label":"Facebook","url":"https://facebook.com"},{"label":"X","url":"https://x.com"},{"label":"Instagram","url":"https://instagram.com"}]')
on conflict (key) do nothing;

insert into public.team_members (name, role, bio, image_url, sort_order)
select 'Demo User', 'Founder & CEO', 'Passionate about making technology accessible to everyone.', '', 1
where not exists (select 1 from public.team_members);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'bytecart-assets',
  'bytecart-assets',
  true,
  52428800,
  array['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml', 'video/mp4', 'video/webm']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists bytecart_assets_read_public on storage.objects;
create policy bytecart_assets_read_public on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'bytecart-assets');
drop policy if exists bytecart_assets_admin_insert on storage.objects;
create policy bytecart_assets_admin_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'bytecart-assets' and (select public.is_admin()));
drop policy if exists bytecart_assets_admin_update on storage.objects;
create policy bytecart_assets_admin_update on storage.objects
  for update to authenticated
  using (bucket_id = 'bytecart-assets' and (select public.is_admin()))
  with check (bucket_id = 'bytecart-assets' and (select public.is_admin()));
drop policy if exists bytecart_assets_admin_delete on storage.objects;
create policy bytecart_assets_admin_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'bytecart-assets' and (select public.is_admin()));

-- After registering your account, promote the first administrator in the SQL Editor:
-- update public.profiles set role = 'admin' where email = 'your-email@example.com';
